wakralabconsulting/qmapp

QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/ReusableComponents/CommonColours/QMColours.swift, QatarMuseum/ViewController/FilterViewController.swift, QatarMuseum/ViewController/HomeViewController.swift, QatarMuseum/ViewController/SettingsViewController.swift, QatarMuseum/ar.lproj/Localizable.strings, QatarMuseum/en.lproj/Localizable.strings, QatarMuseums.xcodeproj/project.pbxproj
=> Adding SettingsPage

Podfile.lock, QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/ReusableComponents/FSCalendar/FSCalendar+Deprecated.m, QatarMuseum/ReusableComponents/FSCalendar/FSCalendar.h, QatarMuseum/ReusableComponents/FSCalendar/FSCalendar.m, QatarMuseum/ReusableComponents/FSCalendar/FSCalendarAppearance.m, QatarMuseum/ReusableComponents/FSCalendar/FSCalendarHeaderView.m, QatarMuseum/ReusableComponents/FSCalendar/FSCalendarWeekdayView.m, QatarMuseum/ViewController/EducationViewController.swift, QatarMuseum/ViewController/EventViewController.swift, QatarMuseum/ViewController/FilterViewController.swift, QatarMuseum/ViewController/SettingsViewController.swift, QatarMuseums.xcodeproj/project.pbxproj, podfile
Adding RTL Calendar Issues Solutions
=> Adding RTL Calendar Issues Solutions

QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/ReusableComponents/CommonMethods/QMFont.swift, QatarMuseum/ReusableComponents/DiningDetailCell/DiningDetailTableViewCell.swift
=> Adding DiningPage RTL Issue

QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/ReusableComponents/HeritageDetailCell/HeritageDetailCell.swift
=> Adding Modifications

QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/ReusableComponents/BottomSheet/MapDetailView.swift, QatarMuseum/ReusableComponents/BottomSheet/ObjectPopupView.xib, QatarMuseum/ReusableComponents/ObjectImageView/ObjectImageView.swift, QatarMuseum/ReusableComponents/ObjectImageView/ObjectImageXib.xib, QatarMuseum/ViewController/FloorMapViewController.swift, QatarMuseum/ViewController/ObjectDetailViewController.swift
- Modified zoom in ObjectImageView
- Added "View Detail" Label in ObjectPopupView
- Added Close button and functionality in ObjectPopupView
=> Adding TourGuidePopupChanges

QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/ReusableComponents/BottomSheet/ObjectPopupTableViewCell.swift, QatarMuseum/ReusableComponents/BottomSheet/ObjectPopupView.xib, QatarMuseum/ReusableComponents/ObjectDetailCell/ObjectDetailTableViewCell.swift, QatarMuseum/ReusableComponents/ObjectPopup/ObjectPopupXib.xib, QatarMuseum/ViewController/FloorMapViewController.swift, QatarMuseum/ViewController/PreviewContainerViewController.swift, QatarMuseum/ViewController/PreviewContentViewController.swift, QatarMuseum/ViewController/PreviewPageViewController.swift
- Modified ScienceTour ,
-  Modified FloorMap
=> Modified ScienceTour, Modified FloorMap

QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/ReusableComponents/ComingSoonPopup/ComingSoonPopUp.swift, QatarMuseum/ReusableComponents/HomeCollectionCell/HomeCollectionViewCell.swift, QatarMuseum/ViewController/MiaTourGuideViewController.swift, QatarMuseum/ViewController/MuseumsViewController.swift, QatarMuseum/ViewController/TourGuideViewController.swift, QatarMuseum/ar.lproj/Localizable.strings, QatarMuseum/en.lproj/Localizable.strings
- Added Tour guide icon for Mathaf and National Museum in Home Page and Museum Landing Page, - Changed Button and Text Color in Tour Guide Page"
=> Added Tour guide icon for Mathaf and National Museum in Home Page and Museum Landing Page, Changed Button and Text Color in Tour Guide Page" 

QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/ReusableComponents/BottomSheet/MapDetailCell.xib, QatarMuseum/ReusableComponents/ObjectDetailCell/ObjectDetailTableViewCell.swift, QatarMuseum/ViewController/DiningViewController.swift, QatarMuseum/ViewController/EducationViewController.swift, QatarMuseum/ViewController/EventViewController.swift, QatarMuseum/ViewController/ExhibitionsViewController.swift, QatarMuseum/ViewController/HeritageListViewController.swift, QatarMuseum/ViewController/HomeViewController.swift, QatarMuseum/ViewController/MuseumsViewController.swift, QatarMuseum/ViewController/PublicArtsViewController.swift, QatarMuseum/ViewController/TourGuideViewController.swift
loading audio text and navigation from burger icon page
=> Tour guide 02

QatarMuseum/AppDelegate.swift, QatarMuseum/ReusableComponents/VersaPlayer/Classes/VersaPlayer.swift, QatarMuseum/ViewController/MuseumAboutViewController.swift
fixed fullscreen landscape issue
=> fixed fullscreen landscape issue

QatarMuseum/ViewController/DiningDetailViewController.swift
=> dining carousalimage

QatarMuseum/AppDelegate.swift, QatarMuseum/ViewController/NotificationsViewController.swift
handled push notification while app is terminated
=> handled push notification while app is terminated

QatarMuseum/ReusableComponents/NMoQHeader/NMoHeaderView.xib, QatarMuseum/ReusableComponents/NMoQHeader/NMoQHeaderCell.swift, QatarMuseum/ViewController/CulturePassViewController.swift, QatarMuseum/ViewController/HomeViewController.swift, QatarMuseum/ViewController/ProfileViewController.swift, QatarMuseums.xcodeproj/project.pbxproj
Resolved Bugs in HomePageBanner
=> Resolved Bugs in HomePageBanner

QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/ReusableComponents/PanelDiscussionDetailView/PanelDetailCell.swift, QatarMuseum/ReusableComponents/PanelDiscussionDetailView/PanelDetailView.xib, QatarMuseum/ViewController/NMoQTourViewController.swift, QatarMuseum/ViewController/PanelDiscussionDetailViewController.swift, QatarMuseum/ViewController/TourAndPanelListViewController.swift, QatarMuseums.xcodeproj/project.pbxproj
=> Added TourDetailPageUI

QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/ViewController/MuseumAboutViewController.swift
=> Resolved Bugs in Travel Page

QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/Models/NMoQTour.swift, QatarMuseum/ReusableComponents/NMoQListCell/NMoQListCell.swift, QatarMuseum/ReusableComponents/NMoQListCell/NMoQListCell.xib, QatarMuseum/ReusableComponents/NMoQTourDescriptionCell/NMoQTourDescriptionCell.xib, QatarMuseum/Services/QatarMuseumRouter.swift, QatarMuseum/ViewController/HomeViewController.swift, QatarMuseum/ViewController/MuseumAboutViewController.swift, QatarMuseum/ViewController/MuseumsViewController.swift, QatarMuseum/ViewController/TourAndPanelListViewController.swift, QatarMuseums.xcodeproj/project.pbxproj
=> Added NMoQTourList Api

QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/DetailPageStoryboard.storyboard, QatarMuseum/Models/HomeBanner.swift, QatarMuseum/ReusableComponents/HeritageDetailCell/MuseumAboutCell.swift, QatarMuseum/ReusableComponents/TravelCell/TravelCollectionViewCell.swift, QatarMuseum/Services/QatarMuseumRouter.swift, QatarMuseum/ViewController/MuseumAboutViewController.swift, QatarMuseum/ViewController/TravelArrangementsViewController.swift, QatarMuseum/ar.lproj/Localizable.strings, QatarMuseum/en.lproj/Localizable.strings
Added TravelList Api and Detail page
=> Added TravelList Api and Detail page

QatarMuseum/AppDelegate.swift, QatarMuseum/DetailPageStoryboard.storyboard, QatarMuseum/QatarMuseums.xcdatamodeld/QatarMuseums.xcdatamodel/contents, QatarMuseum/ViewController/TourAndPanelListViewController.swift
Optimisation in NMoQSpecialEventList
=> Optimisation in NMoQSpecialEventList

QatarMuseum/AppDelegate.swift, QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/ReusableComponents/CommonMethods/QMUtility.swift, QatarMuseum/ViewController/CulturePassCardViewController.swift, QatarMuseum/ViewController/DiningViewController.swift, QatarMuseum/ViewController/EventViewController.swift, QatarMuseum/ViewController/ExhibitionDetailViewController.swift, QatarMuseum/ViewController/FloorMapViewController.swift, QatarMuseum/ViewController/HeritageDetailViewController.swift, QatarMuseum/ViewController/HomeViewController.swift, QatarMuseum/ViewController/MiaTourGuideViewController.swift, QatarMuseum/ViewController/NotificationsViewController.swift, QatarMuseum/ViewController/ProfileViewController.swift, QatarMuseum/ViewController/TourAndPanelListViewController.swift, QatarMuseum/ViewController/TourGuideViewController.swift, QatarMuseums.xcodeproj/xcuserdata/exalturemacair.xcuserdatad/xcschemes/QatarMuseums.xcscheme
Removed barcode and number from CulturePassCard, Modified SpecialEventList Page, Resolved Bugs
=> Removed barcode and number from CulturePassCard, Modified SpecialEventList Page, Resolved Bugs

QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/DetailPageStoryboard.storyboard, QatarMuseum/ReusableComponents/HeritageDetailCell/MuseumAboutCell.swift, QatarMuseum/ReusableComponents/ObjectDetailCell/ObjectDetailTableViewCell.swift, QatarMuseum/ViewController/MuseumAboutViewController.swift, QatarMuseum/ViewController/MuseumsViewController.swift
=> Resolved Bugs

QatarMuseum/AppDelegate.swift, QatarMuseum/Base.lproj/Main.storyboard, QatarMuseum/DetailPageStoryboard.storyboard, QatarMuseum/Info.plist, QatarMuseum/Models/Museum.swift, QatarMuseum/Models/NMoQTourDetail.swift, QatarMuseum/Models/NMoQUserEventList.swift, QatarMuseum/QatarMuseums.xcdatamodeld/QatarMuseums.xcdatamodel/contents, QatarMuseum/ReusableComponents/ComingSoonPopup/ComingSoonPopUp.swift, QatarMuseum/ReusableComponents/CommonMethods/CommonStrings.swift, QatarMuseum/ReusableComponents/EventPopup/EventPopUp.xib, QatarMuseum/ReusableComponents/EventPopup/EventPopupView.swift, QatarMuseum/ReusableComponents/HeritageDetailCell/MuseumAboutCell.swift, QatarMuseum/ReusableComponents/PanelDiscussionDetailView/PanelDetailCell.swift, QatarMuseum/ReusableComponents/PanelDiscussionDetailView/PanelDetailView.xib, QatarMuseum/ViewController/CulturePassViewController.swift, QatarMuseum/ViewController/HeritageDetailViewController.swift, QatarMuseum/ViewController/HomeViewController.swift, QatarMuseum/ViewController/MuseumAboutViewController.swift, QatarMuseum/ViewController/MuseumsViewController.swift, QatarMuseum/ViewController/NMoQTourViewController.swift, QatarMuseum/ViewController/PanelDiscussionDetailViewController.swift, QatarMuseum/ar.lproj/Localizable.strings, QatarMuseum/en.lproj/Localizable.strings
=> Modified NMoQ Pages

QatarMuseum/Models/NMoQTourDetail.swift, QatarMuseum/Models/NMoQUserEventList.swift, QatarMuseum/ReusableComponents/PanelDiscussionDetailView/PanelDetailCell.swift, QatarMuseum/ViewController/PanelDiscussionDetailViewController.swift, QatarMuseum/ViewController/TourAndPanelListViewController.swift
=> Modified TourDetail

QatarMuseum/ReusableComponents/ComingSoonPopup/ComingSoonPopUp.swift, QatarMuseum/ReusableComponents/CommonMethods/CommonStrings.swift, QatarMuseum/ReusableComponents/EventPopup/EventPopupView.swift, QatarMuseum/ReusableComponents/HeritageDetailCell/MuseumAboutCell.swift, QatarMuseum/ReusableComponents/NMoQHeader/NMoHeaderView.xib, QatarMuseum/ReusableComponents/PanelDiscussionDetailView/PanelDetailCell.swift, QatarMuseum/ReusableComponents/RsvpPopups/AcceptDeclinePopup.swift, QatarMuseum/ViewController/PanelDiscussionDetailViewController.swift, QatarMuseum/ViewController/ProfileViewController.swift, QatarMuseum/ar.lproj/Localizable.strings, QatarMuseum/en.lproj/Localizable.strings
Modified strings in NMoQTourDetailPage
=> Modified strings in NMoQTourDetailPage

QatarMuseum/ReusableComponents/PanelDiscussionDetailView/PanelDetailCell.swift, QatarMuseum/ViewController/PanelDiscussionDetailViewController.swift, QatarMuseum/ar.lproj/Localizable.strings, QatarMuseum/en.lproj/Localizable.strings, QatarMuseums.xcworkspace/xcuserdata/exalturemacair.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
=> Modified popupstrings
